---
name: aws.elb_get_all_attributes
pack: aws
description: Web hook to list all the attributes
enabled: true

trigger:
        type: "core.st2.webhook"
        parameters:
            url: "elbattributes"
criteria:
    trigger.body.key1:
        type: "equals"
        pattern: "value1"

action:
    ref: aws.elb_get_all_lb_attributes
    parameters:
